name: CI

on:
    push:
        branches: ["master"]


permissions: write-all


jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            
            # -   name: Install Appwrite CLI Polyfill
            #     shell: bash
            #     working-directory: ./.polyfill
            #     run: |
            #       chmod +x appwrite.sh
            #       ./appwrite.sh

            -   name: Install Appwrite CLI
                shell: bash
                run: |
                    curl -sL https://appwrite.io/cli/install.sh | bash

            # -   name: Appwrite Version
            #     shell: bash
            #     run: |
            #         appwrite -v
            #         ls

            -   name: Appwrite Deployment
                shell: bash
                working-directory: ./functions/register
                run: |
                    appwrite client \
                    --endpoint='https://panel.appwrite.io/v1' \
                    --projectId='kbve' \
                    --key='${{ secrets.APPWRITE_PANEL }}'

                    appwrite -v
#                    appwrite functions createDeployment \
#                    --functionId=register \
#                    --entrypoint='index.js' \
#                    --code='.' \
#                    --activate=true